const content = {
  en: {
    language: 'English',
    timeIntervals: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', yearly: 'Yearly' },
    interest: 'Interest',
    installments: 'Installments',
    taxes: 'Taxes',
    complexCompounding: 'Complex Compounding Interest',
    principal: 'Principal',
    rate: 'Rate',
    period: 'Period',
    count: 'Count',
    kkdfRate: 'KKDF Rate',
    bsmvRate: 'BSMV Rate',
    enable: 'Enable',
    calculatePayment: 'Calculate Payment',
    createPaymentPlan: 'Create Payment Plan',
    compoundingPeriodFootnote: 'Use these fields if compounding period is different to the payment period.',
    tableHeaders: {
      installmentNo: 'Installment Number',
      installmentAmount: 'Installment Amount',
      principalPaid: 'Principal Paid',
      remainingPrincipal: 'Remaining Principal',
      paidInterest: 'Paid Interest',
      kkdf: 'KKDF',
      bsmv: 'BSMV',
    },
    monthlyPayment: 'Monthly\xa0payment',
    totalPayment: 'Total\xa0payment',
    kkdfAmount: 'KKDF\xa0amount',
    bsmvAmount: 'BSMV\xa0amount',
    totalTaxes: 'Total\xa0taxes',
  },
  tr: {
    language: 'Türkçe',
    timeIntervals: { daily: 'Günlük', weekly: 'Haftalık', monthly: 'Aylık', yearly: 'Yıllık' },
    interest: 'Faiz',
    installments: 'Ödemeler',
    taxes: 'Vergiler',
    complexCompounding: 'Bileşik Faiz Uygulaması',
    principal: 'Ana Para',
    rate: 'Oran',
    period: 'Periyot',
    count: 'Sayı',
    kkdfRate: 'KKDF Oranı',
    bsmvRate: 'BSMV Oranı',
    enable: 'Kullan',
    calculatePayment: 'Ödemeyi Hesapla',
    createPaymentPlan: 'Ödeme Planı Oluştur',
    compoundingPeriodFootnote: 'Faiz uygulama aralığı ödeme aralığından farklı ise bu alanları kullanın.',
    tableHeaders: {
      installmentNo: 'Taksit No',
      installmentAmount: 'Taksit Tutarı',
      principalPaid: 'Ödenen Ana Para',
      remainingPrincipal: 'Kalan Ana Para',
      paidInterest: 'Ödenen Faiz',
      kkdf: 'KKDF',
      bsmv: 'BSMV',
    },
    monthlyPayment: 'Aylık\xa0taksit\xa0tutarı',
    totalPayment: 'Toplam\xa0geri\xa0ödeme',
    kkdfAmount: 'KKDF\xa0tutarı',
    bsmvAmount: 'BSMV\xa0tutarı',
    totalTaxes: 'Toplam\xa0vergiler',
  },
};

export default content;
