const content = {
  en: {
    language: 'English',
    timeIntervals: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', yearly: 'Yearly' },
    principal: 'Principal',
    interestRate: 'Interest Rate',
    ratePeriod: 'Rate Period',
    installmentCount: 'Installment Count',
    installmentPeriod: 'Installment Period',
    kkdfRate: 'KKDF Rate',
    bsmvRate: 'BSMV Rate',
    compoundingPeriod: 'Compounding Period',
    calculatePayment: 'Calculate Payment',
    createPaymentPlan: 'Create Payment Plan',
    compoundingPeriodFootnote: 'Use these fields if compounding period is different to the payment period.',
    tableHeaders: {
      installmentNo: 'Installment Number',
      installmentAmount: 'Installment Amount',
      principalPaid: 'Principal Paid',
      remainingPrincipal: 'Remaining Principal',
      paidInterest: 'Paid Interest',
      kkdf: 'KKDF',
      bsmv: 'BSMV',
    },
    monthlyPayment: 'Monthly payment',
    totalPayment: 'Total payment',
    kkdfAmount: 'KKDF amount',
    bsmvAmount: 'BSMV amount',
    totalTaxes: 'Total taxes',
  },
  tr: {
    language: 'Türkçe',
    timeIntervals: { daily: 'Günlük', weekly: 'Haftalık', monthly: 'Aylık', yearly: 'Yıllık' },
    principal: 'Ana Para',
    interestRate: 'Faiz Oranı',
    ratePeriod: 'Oran Cinsi',
    installmentCount: 'Taksit Sayısı',
    installmentPeriod: 'Taksit Aralığı',
    kkdfRate: 'KKDF Oranı',
    bsmvRate: 'BSMV Oranı',
    compoundingPeriod: 'Faiz Aralığı',
    calculatePayment: 'Ödemeyi Hesapla',
    createPaymentPlan: 'Ödeme Planı Oluştur',
    compoundingPeriodFootnote: 'Faiz uygulama aralığı ödeme aralığından farklı ise bu alanları kullanın.',
    tableHeaders: {
      installmentNo: 'Taksit No',
      installmentAmount: 'Taksit Tutarı',
      principalPaid: 'Ödenen Ana Para',
      remainingPrincipal: 'Kalan Ana Para',
      paidInterest: 'Ödenen Faiz',
      kkdf: 'KKDF',
      bsmv: 'BSMV',
    },
    monthlyPayment: 'Aylık taksit tutarı',
    totalPayment: 'Toplam geri ödeme',
    kkdfAmount: 'KKDF tutarı',
    bsmvAmount: 'BSMV tutarı',
    totalTaxes: 'Toplam vergiler',
  },
};

export default content;
